build:
    requirements: {}
dependencies: {}
sources:
    cohort10:
        description: data for 2009-10
        filetype: csv
        row_spec:
            data_start_line: 1
            header_lines:
            - 0
        space: California
        table: cohort
        time: 2010
        url: http://dq.cde.ca.gov/dataquest/dlfile/dlfile.aspx?cLevel=All&cYear=2009-10&cCat=Cohort&cPage=filescohort
    cohort11:
        description: data for 2010-11
        filetype: csv
        row_spec:
            data_start_line: 1
            header_lines:
            - 0
        space: California
        table: cohort
        time: 2011
        url: http://dq.cde.ca.gov/dataquest/dlfile/dlfile.aspx?cLevel=All&cYear=2010-11&cCat=Cohort&Cpage=filescohort
    cohort12:
        description: data for 2011-12
        filetype: csv
        row_spec:
            data_start_line: 1
            header_lines:
            - 0
        space: California
        table: cohort
        time: 2012
        url: http://dq.cde.ca.gov/dataquest/dlfile/dlfile.aspx?cLevel=All&cYear=2011-12&cCat=Cohort&Cpage=filescohort
    cohort13:
        description: data for 2012-13
        filetype: csv
        row_spec:
            data_start_line: 1
            header_lines:
            - 0
        space: California
        table: cohort
        time: 2013
        url: http://dq.cde.ca.gov/dataquest/dlfile/dlfile.aspx?cLevel=All&cYear=2012-13&cCat=Cohort&Cpage=filescohort
    cohort14:
        description: data for 2013-14
        filetype: csv
        row_spec:
            data_start_line: 1
            header_lines:
            - 0
        space: California
        table: cohort
        time: 2014
        url: http://dq.cde.ca.gov/dataquest/dlfile/dlfile.aspx?cLevel=All&cYear=2013-14&cCat=Cohort&Cpage=filescohort
views: {}
